### ISSUE TITLE
Wishlist: Pfizer 47k HTE dataset

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-data#158]
https://chemrxiv.org/engage/chemrxiv/article-details/63581205aca1989b92e4d77c

Status: data will be released upon publication

**Comment by bdeadman** [comment]
This dataset is getting close to submission now. There is now a basic dataset (39k reactions) which passes essential validation checks. There are however some chemical inputs (including solvent) which are only defined by name (no SMILES). I'm going to attempt to add in the SMILES for the most common recurring chemicals so rdkit can index them.

<img width="656" alt="image" src="https://github.com/open-reaction-database/ord-data/assets/30119869/16c388a6-b631-4c22-97f9-f5bac9b53a66">

<img width="646" alt="image" src="https://github.com/open-reaction-database/ord-data/assets/30119869/ab9bc2b7-5787-413a-9b40-21877440267f">

<img width="646" alt="image" src="https://github.com/open-reaction-database/ord-data/assets/30119869/4f96d29f-a6b7-45ec-8ff4-ca6507d23c5b">

**Comment by bdeadman** [comment]
Complete in #189
