### ISSUE TITLE
USPTO Dataset Question

### ISSUE THREAD

**Issue by Peggy-Li** [open-reaction-database/ord-data#181]
How much of the Lowe USPTO dataset is in ORD? I saw in the 0.1.0 release note that you included the grants data. Does that mean there is no data from the applications (Like 2001-2016 applications from https://figshare.com/articles/dataset/Chemical_reactions_from_US_patents_1976-Sep2016_/5104873) Are grants and applications a very close match in their contents?

Thanks.

**Comment by skearnes** [comment]
Hi, you are correct that we've only included the grant data. Most of the published retrosynthesis ML literature uses a subset of the grants data, which is why we focused on that.

**Comment by skearnes** [comment]
@connorcoley may have more to say about the contrast between grants and applications?

**Comment by connorcoley** [comment]
I don't have anything specific to add; we focused on the grant data as a key set that is often used for downstream modeling tasks

For the years in common, we do expect a very very high degree of overlap between data from grants and data from applications

**Comment by Peggy-Li** [comment]
Thanks for the clarification!
