### ISSUE TITLE
Chemical catalyst

### ISSUE THREAD

**Issue by le-yuan** [open-reaction-database/ord-data#182]
Thanks for developing this great platform for chemical reaction. I have one question: how to get chemical catalyst for one specific reaction? Is it possible to get it from reaction_role? Looking forward to your reply. Thanks!

**Comment by bdeadman** [comment]
Hi @le-yuan, thanks for your interest in the ORD. 

If you are looking in the .pbtxt files for a specific dataset then it is "reation_role: CATALYST" that you want to search for.

If you are using the browser at [](https://open-reaction-database.org/browse) then you can see the "catalyst" label under the Role column of the components table. Note that the "Catalyst" input is an arbitrary label attached by submitter so this may not always be catalyst. This screenshot is taken from [](https://open-reaction-database.org/id/ord-058a3137f3e54649b663eca49d7b37d8)
<img width="485" alt="image" src="https://github.com/open-reaction-database/ord-data/assets/30119869/4202d6f0-bc91-41be-a648-ef169a3215c6">

At present there isn't a good to search for catalyst in the browser/search interface. This is something we are working on for an update in the near future. If you want to search for catalysts then you could however build your own local version of the ORD database (see [](https://github.com/open-reaction-database/ord-interface)) and then search the PostgreSQL database using SQL. The reaction_role field is in the ord.compound table. Get in touch if you want some extra support to do this.

For all the above, it should be noted that for mined reaction data (e.g. the USPTO datasets) the labelling of reaction_role can be less reliable than the curated datasets. So in some cases the mined data may have catalysts labelled as "reactant" instead.

**Comment by le-yuan** [comment]
Thanks for your so quick reply. I'll check it based on your answers.

**Comment by bdeadman** [comment]
No problem @le-yuan . Please let me know how it goes, and then I will close off this issue once we are confident one of my answers worked for you.

**Comment by bdeadman** [comment]
Issue resolved.
